version: "3.3"

services:
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py initial_django_setup &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery-worker:
    restart: always
    build:
      context: .
    command: celery -A mopProject worker -l DEBUG
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    restart: always
    build:
      context: .
    #command: celery -A mopProject beat -l DEBUG
    command: celery -A mopProject beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: