# Generated by Django 3.2.6 on 2021-08-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'financial_symbol',
            },
        ),
    ]
