# Generated by Django 3.2.6 on 2021-08-05 15:01

from django.db import migrations


def insert_default_symbols(apps, schema_editor):
    default_symbols = ({
                           'symbol': 'AAPL',
                           'name': 'Apple Inc.'
                       },
                       {
                           'symbol': 'TWTR',
                           'name': 'Twitter, Inc.'
                       },
                       {
                           'symbol': 'GC=F',
                           'name': 'Gold Dec 21'
                       },
                       {
                           'symbol': 'INTC',
                           'name': 'Intel Corporation'
                       })

    FinancialSymbol = apps.get_model('financial_news', 'FinancialSymbol')
    for f_symbol in default_symbols:
        fs = FinancialSymbol()
        fs.symbol = f_symbol['symbol']
        fs.name = f_symbol['name']
        fs.save()


class Migration(migrations.Migration):
    dependencies = [
        ('financial_news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_default_symbols),
    ]
