# Generated by Django 3.2.6 on 2021-08-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('financial_news', '0003_financialnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsymbol',
            name='scraping_on',
            field=models.BooleanField(default=True),
        ),
    ]
